#ifndef CPP2_S21_CONTAINERS_SRC_S21_CONTAINERS_H_
#define CPP2_S21_CONTAINERS_SRC_S21_CONTAINERS_H_

#include "s21_deque.h"
#include "s21_stack.h"

#endif  // CPP2_S21_CONTAINERS_SRC_S21_CONTAINERS_H_
